# Generated by Django 3.0 on 2020-03-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe',
            field=models.TextField(max_length=500),
        ),
    ]
